### ISSUE TITLE
Download interaction files gives timeout in production

### ISSUE THREAD

**Issue by juanboca** [instedd/surveda#1455]
Also when running the tests locally, there are 2 tests that consistently fail giving db timeout error.

```2019-02-01T19:27:44.444Z [error] Mariaex.Protocol (#PID<0.414.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.454.0> timed out because it owned the connection for longer than 15000ms


  1) test download download interactions (Ask.RespondentControllerTest)
     test/controllers/respondent_controller_test.exs:1261
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :ets.update_counter(#Reference<0.1724783726.2043543553.180599>, :__counter__, {2, 1})
       (mariaex) lib/mariaex/lru_cache.ex:73: Mariaex.LruCache.increment/1
       (mariaex) lib/mariaex/lru_cache.ex:49: Mariaex.LruCache.insert_new/5
       (mariaex) lib/mariaex/protocol.ex:874: Mariaex.Protocol.deallocate_insert/3
       (mariaex) lib/mariaex/protocol.ex:859: Mariaex.Protocol.deallocate/3
       (ecto) lib/ecto/adapters/sql/sandbox.ex:359: Ecto.Adapters.SQL.Sandbox.Connection.proxy/3
       (db_connection) lib/db_connection.ex:958: DBConnection.handle/4
       (db_connection) lib/db_connection.ex:1142: anonymous fn/4 in DBConnection.run_meter/5
       (db_connection) lib/db_connection.ex:1501: DBConnection.deallocate/4
       (elixir) lib/stream.ex:1278: Stream.do_resource/5
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/stream.ex:806: Stream.do_transform/8
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/stream.ex:870: Stream.do_enum_transform/10
       (elixir) lib/stream.ex:806: Stream.do_transform/8
       (elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
       (elixir) lib/enum.ex:1823: Enum.reduce/3
       (ecto) lib/ecto/adapters/sql.ex:620: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1275: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1199: DBConnection.run_begin/3```

**Comment by waj** [comment]
Fixed in 0.21.2
