### ISSUE TITLE
MyXQL throws "Unknown column 'ecto_Ask.Repo' in 'field list'" with ANSI_QUOTES turned on

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/surveda#2140]
When trying to run Surveda (tested in 81e613b6109c847c600689433d0020684928f7ae and a00289bed2aa5a365863c0c5377b58748419f747) with MySQL 5.7 (tested with 5.7.22 and 5.7.33) with [the `ANSI_QUOTES` SQL mode on](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes), Ecto fails with this error:

```
** (MatchError) no match of right hand side value: {:error, %MyXQL.Error{connection_id: 95080, message: "Unknown column 'ecto_Ask.Repo' in 'field list'", mysql: %{code: 1054, name: nil}, statement: "SELECT RELEASE_LOCK(\"ecto_Ask.Repo\")"}}
    (ecto_sql) lib/ecto/adapters/myxql.ex:244: Ecto.Adapters.MyXQL."-lock_for_migrations/3-after$^0/0-0-"/3
    (ecto_sql) lib/ecto/adapters/myxql.ex:240: anonymous fn/4 in Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql) lib/ecto/adapters/sql.ex:1021: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
    (db_connection) lib/db_connection.ex:1512: DBConnection.run_transaction/4
    (ecto_sql) lib/ecto/adapters/myxql.ex:237: Ecto.Adapters.MyXQL.lock_for_migrations/3
    (ecto_sql) lib/ecto/migrator.ex:526: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql) lib/ecto/migrator.ex:419: Ecto.Migrator.run/4
    (ecto_sql) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
```

This can be triggered by running `mix ecto.migrations`.

The behaviour can easily be reproduced in pure SQL by trying this query with or without `ANSI_QUOTES` turned:

```sql
SELECT RELEASE_LOCK("ecto_Ask.Repo"); -- this will fail with ANSI_QUOTES, and return NULL without ANSI_QUOTES
```

We should investigate if it's an Ecto/MyXQL issue, or if we're missing a setting in the DB connection, and learn to address it.

**Comment by matiasgarciaisaia** [comment]
We found this issue in production, with two AWS RDS databases running MySQL 5.7.33 with a parameter group named `rails-compatible` that enabled this SQL Mode among others. This is the full value of `sql_mode`:

```
ALLOW_INVALID_DATES,ANSI_QUOTES,ERROR_FOR_DIVISION_BY_ZERO,HIGH_NOT_PRECEDENCE,IGNORE_SPACE,NO_AUTO_CREATE_USER,NO_DIR_IN_CREATE,NO_ENGINE_SUBSTITUTION,NO_FIELD_OPTIONS,NO_KEY_OPTIONS,NO_TABLE_OPTIONS,NO_UNSIGNED_SUBTRACTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,PAD_CHAR_TO_FULL_LENGTH,PIPES_AS_CONCAT,REAL_AS_FLOAT,STRICT_ALL_TABLES,STRICT_TRANS_TABLES,ANSI,DB2,MAXDB,MSSQL,MYSQL323,MYSQL40,ORACLE,POSTGRESQL,TRADITIONAL
```

**Comment by matiasgarciaisaia** [comment]
This should be fixed in elixir-ecto/ecto_sql#443 - we have to update Surveda to use that.

**Comment by ysbaddaden** [comment]
The commit has been released in `ecto_sql` 3.9.1.

**Comment by ysbaddaden** [comment]
@matiasgarciaisaia @manumoreira I can merge & push this tech upgrade along with the upcoming release, or I can wait and merge it just after with the channel broker.

I'm not expecting anything to break. The patch in #2210 being rather simple.

**Comment by manumoreira** [comment]
IMO we should merge to the upcoming release, but let's see what @matiasgarciaisaia says

**Comment by ysbaddaden** [comment]
QA: to be verified by @matiasgarciaisaia against a MySQL server where ANSI QUOTES at setup.
