### ISSUE TITLE
SurveyBroker crash

### ISSUE THREAD

**Issue by ysbaddaden** [instedd/surveda#2276]
While running yet another run with the Channel Broker, I noticed the following crash of SurveyBroker in the logs:

```
surveda-app-1  | 2023-05-22T19:58:17.588Z [error] GenServer Ask.Runtime.SurveyBroker terminating
surveda-app-1  | ** (stop) exited in: GenServer.call(#PID<0.1356.0>, {:setup, "sms", %Ask.Runtime.NuntiumChannel{base_url: "http://web.nuntium.lvh.me", name: "lgwsim-local - jportalier@manas.tech", oauth_token: %OAuth2.AccessTok
en{access_token: "rdLT0LhXvM7tC5XRB-GhhckC-GIT4DoMGiBXJajwEvE", expires_at: 1684786035, other_params: %{}, refresh_token: "VSiQLPlUAUYEeoUiZU1HSJ7o5SmrXFT7eliWA-9E6LM", token_type: "Bearer"}, settings: %{"capacity" => 100, "nunt
ium_account" => "jportalier@manas.tech", "nuntium_channel" => "lgwsim-local"}}, %Ask.Respondent{phone_number: "100000052", disposition: :queued, canonical_phone_number: "100000052", timeout_at: nil, responses: #Ecto.Association.
NotLoaded<association :responses is not loaded>, state: :pending, inserted_at: ~U[2023-05-22 19:56:05Z], sanitized_phone_number: "100000052", survey_id: 63, experiment_name: nil, retry_stat_id: nil, id: 393157, lock_version: 4,
retry_stat: #Ecto.Association.NotLoaded<association :retry_stat is not loaded>, quota_bucket: #Ecto.Association.NotLoaded<association :quota_bucket is not loaded>, questionnaire_id: 66, section_order: [0], __meta__: #Ecto.Schema
.Metadata<:loaded, "respondents">, user_stopped: false, quota_bucket_id: nil, effective_modes: nil, respondent_group: %Ask.RespondentGroup{__meta__: #Ecto.Schema.Metadata<:loaded, "respondent_groups">, channels: #Ecto.Associatio
n.NotLoaded<association :channels is not loaded>, id: 64, inserted_at: ~U[2023-05-22 19:55:36Z], name: "respondents_100.csv", respondent_group_channels: [%Ask.RespondentGroupChannel{__meta__: #Ecto.Schema.Metadata<:loaded, "resp
ondent_group_channels">, channel: %Ask.Channel{__meta__: #Ecto.Schema.Metadata<:loaded, "channels">, base_url: "http://web.verboice.lvh.me", id: 2, inserted_at: ~U[2023-03-13 16:33:42Z], name: "twiliosim-local", patterns: [], pr
ojects: #Ecto.Association.NotLoaded<association :projects is not loaded>, provider: "verboice", respondent_group_channels: #Ecto.Association.NotLoaded<association :respondent_group_channels is not loaded>, settings: %{"capacity"
 => 2, "verboice_channel" => "twiliosim-local", "verboice_channel_id" => 1}, status: nil, type: "ivr", updated_at: ~U[2023-04-25 12:30:22Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, user_id: 1}, channe
l_id: 2, id: 65, inserted_at: ~U[2023-05-22 19:55:37Z], mode: "ivr", respondent_group: #Ecto.Association.NotLoaded<association :respondent_group is not loaded>, respondent_group_id: 64, updated_at: ~U[2023-05-22 19:55:37Z]}, %As
k.RespondentGroupChannel{__meta__: #Ecto.Schema.Metadata<:loaded, "respondent_group_channels">, channel: %Ask.Channel{__meta__: #Ecto.Schema.Metadata<:loaded, "channels">, base_url: "http://web.nuntium.lvh.me", id: 1, inserted_a
t: ~U[2023-03-10 10:31:56Z], name: "lgwsim-local - jportalier@manas.tech", patterns: [], projects: #Ecto.Association.NotLoaded<association :projects is not loaded>, provider: "nuntium", respondent_group_channels: #Ecto.Associati
on.NotLoaded<association :respondent_group_channels is not loaded>, settings: %{"capacity" => 100, "nuntium_account" => "jportalier@manas.tech", "nuntium_channel" => "lgwsim-local"}, status: nil, type: "sms", updated_at: ~U[2023
-04-11 18:35:39Z], user: #Ecto.Association.NotLoaded<association :user is not loaded>, ...}, channel_id: 1, id: 66, inserted_at: ~U[2023-05-22 19:55:37Z], mode: "sms", respondent_group: #Ecto.Association.NotLoaded<association :r
espondent_group is not loaded>, respondent_group_id: 64, updated_at: ~U[2023-05-22 19:55:37Z]}], respondents: #Ecto.Association.NotLoaded<association :respondents is not loaded>, respondents_count: 10100, sample: ["1000", "1001"
, "1002", "1003", "1004"], survey: #Ecto.Association.NotLoaded<association :survey is not loaded>, survey_id: 63, updated_at: ~U[2023-05-22 19:56:07Z]}, mode: ["sms"], language: nil, session: nil, hashed_number: "r0c77a7e19d99",
 respondent_group_id: 64, survey: #Ecto.Association.NotLoaded<association :survey is not loaded>, updated_at: ~U[2023-05-22 19:58:12Z], questionnaire: #Ecto.Association.NotLoaded<association :questionnaire is not loaded>, comple
ted_at: nil, stats: %Ask.Stats{attempts: %{"sms" => 1}, call_durations: %{}, pending_call: false, total_call_time: nil, total_call_time_seconds: nil, total_received_sms: 0, total_sent_sms: 0}, survey_log_entries: #Ecto.Associati
on.NotLoaded<association :survey_log_entries is not loaded>}, "7e57a60d-817b-4220-983d-937bd3c5ddbd", nil, nil}, 5000)
surveda-app-1  |     ** (EXIT) time out
surveda-app-1  |     (elixir 1.10.4) lib/gen_server.ex:1023: GenServer.call/3
surveda-app-1  |     (ask 0.31.0) lib/ask/runtime/session.ex:432: Ask.Runtime.Session.mode_start/1
surveda-app-1  |     (ask 0.31.0) lib/ask/runtime/survey_broker.ex:304: Ask.Runtime.SurveyBroker.start/2
surveda-app-1  |     lib/mut.ex:262: Mutex.apply_with_lock/3
surveda-app-1  |     (elixir 1.10.4) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
surveda-app-1  |     (elixir 1.10.4) lib/enum.ex:783: Enum.each/2
surveda-app-1  |     (ask 0.31.0) lib/ask/runtime/survey_broker.ex:177: Ask.Runtime.SurveyBroker.poll_survey/3
surveda-app-1  |     (elixir 1.10.4) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
surveda-app-1  |     (elixir 1.10.4) lib/enum.ex:783: Enum.each/2
surveda-app-1  |     (ask 0.31.0) lib/ask/runtime/survey_broker.ex:118: Ask.Runtime.SurveyBroker.poll_active_surveys/1
surveda-app-1  |     (ask 0.31.0) lib/ask/runtime/survey_broker.ex:52: Ask.Runtime.SurveyBroker.handle_info/3
surveda-app-1  |     (stdlib 3.12.1.2) gen_server.erl:637: :gen_server.try_dispatch/4
surveda-app-1  |     (stdlib 3.12.1.2) gen_server.erl:711: :gen_server.handle_msg/6
surveda-app-1  |     (stdlib 3.12.1.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
surveda-app-1  | Last message: :poll
surveda-app-1  | State: nil
surveda-app-1  | 2023-05-22T19:58:17.589Z [info] SurveyBroker started. Default batch size=10000. Limit per minute=100.
```

**Comment by ysbaddaden** [comment]
Likely fixed by #2279
